/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scanner;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileFilter;
import java.io.StringReader;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import scanner.Scanner.*;

/**
 *
 * @author Mario Lara Molina
 */
public class InterfazScanner extends javax.swing.JFrame  {
    
    /**
     * Creates new form InterfazScanner
     */
    public InterfazScanner(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLexico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaErrorSintactico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaSintactico = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoLeer = new javax.swing.JTextArea();
        BotonArchivo = new javax.swing.JButton();
        BtnAnalizar = new javax.swing.JToggleButton();
        BtnLimpiar = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaErrorLexico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaLexico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaLexico);

        TablaErrorSintactico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaErrorSintactico);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Analisis Lexico");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tabla de errores sintactico");

        TablaSintactico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaSintactico);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Analisis Sintactico");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Texto por analizar");

        textoLeer.setColumns(20);
        textoLeer.setRows(5);
        jScrollPane4.setViewportView(textoLeer);

        BotonArchivo.setText("Buscar archivo");
        BotonArchivo.setToolTipText("");
        BotonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArchivoActionPerformed(evt);
            }
        });

        BtnAnalizar.setText("Analizar");
        BtnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnalizarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tabla errores lexico");

        TablaErrorLexico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(TablaErrorLexico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BotonArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel6)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(BtnAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BotonArchivo))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Scanner scanner = new Scanner();
    private void BotonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArchivoActionPerformed
        // TODO add your handling code here:
        /*JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Files", "txt"));
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);

        try {
            Reader lector;
            scanner.readFile(chooser.getSelectedFile().getAbsolutePath());
            scanner.organizador();      //Se organiza la lista de Tokens

            String columnsTokens[] = {"Token","Tipo","Linea(s)"};
            String columnsErrors[] = {"Error", "Linea"};
            String datosTokens[][] = new String[scanner.getTokensList().size()][3];
            String datosErrores[][] = new String[scanner.getErrores().size()][3];
            for (int i = 0; i < scanner.getTokensList().size(); i++) {
                String prnt = (String) scanner.getTokensList().get(i).get(0);
                String prnt2 = (String) scanner.getTokensList().get(i).get(1);
                String prnt3 = (String) scanner.getTokensList().get(i).get(2);
                datosTokens[i][0]= prnt;
                datosTokens[i][1]= prnt2;
                datosTokens[i][2]= prnt3;
            }
            for (int i = 0; i < scanner.getErrores().size(); i++) {
                String prnt = (String) scanner.getErrores().get(i).get(0);
                String prnt2 = (String) scanner.getErrores().get(i).get(1);
                datosErrores[i][0]= prnt;
                datosErrores[i][1]= prnt2;
            }
            DefaultTableModel modelTokens = new DefaultTableModel(datosTokens,columnsTokens);
            DefaultTableModel modelErrors = new DefaultTableModel(datosErrores,columnsErrors);
            TablaToken.setModel(modelTokens);
            TablaError.setModel(modelErrors);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(InterfazScanner.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazScanner.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
        
        try {
            String ST = new String(Files.readAllBytes(archivo.toPath()));
            textoLeer.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InterfazScanner.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazScanner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonArchivoActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        textoLeer.setText(null);
        TablaLexico.removeAll();
        TablaErrorSintactico.removeAll();
        TablaSintactico.removeAll();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnalizarActionPerformed
        // TODO add your handling code here:
        String datosPrueba[][] = new String[3][3];
        int cont = 1;
        
        String expr = (String) textoLeer.getText();
        Lexer lexer = new Lexer(new StringReader(expr));
        String resultado = "LINEA " + cont + "\t\tSIMBOLO\n";
        while (true) {
            try {
                Tokens token = lexer.yylex();
                if (token == null) {
                    textoLeer.setText(resultado);
                    return;
                }
                switch (token) {
                    case Array:
                        cont++;
                        resultado += "Array " + cont + "\n";
                        break;
                        /*case Comillas:
                        resultado += "  <Comillas>\t\t" + lexer.lexeme + "\n";
                        break;
                        case Cadena:
                        resultado += "  <Tipo de dato>\t" + lexer.lexeme + "\n";
                        break;
                        case T_dato:
                        resultado += "  <Tipo de dato>\t" + lexer.lexeme + "\n";
                        break;*/
                    case If:
                        resultado += "  <Reservada if>\t" + lexer.lexeme + "\n";
                        break;
                    case Else:
                        resultado += "  <Reservada else>\t" + lexer.lexeme + "\n";
                        break;
                    case Do:
                        resultado += "  <Reservada do>\t" + lexer.lexeme + "\n";
                        break;
                    case While:
                        resultado += "  <Reservada while>\t" + lexer.lexeme + "\n";
                        break;
                    case For:
                        resultado += "  <Reservada for>\t" + lexer.lexeme + "\n";
                        break;
                    case Igual:
                        resultado += "  <Operador igual>\t" + lexer.lexeme + "\n";
                        break;
                    case Suma:
                        resultado += "  <Operador suma>\t" + lexer.lexeme + "\n";
                        break;
                    case Resta:
                        resultado += "  <Operador resta>\t" + lexer.lexeme + "\n";
                        break;
                    case Multiplicacion:
                        resultado += "  <Operador multiplicacion>\t" + lexer.lexeme + "\n";
                        break;
                    case Division:
                        resultado += "  <Operador division>\t" + lexer.lexeme + "\n";
                        break;
                        /*case Op_logico:
                        resultado += "  <Operador logico>\t" + lexer.lexeme + "\n";
                        break;
                        case Op_incremento:
                        resultado += "  <Operador incremento>\t" + lexer.lexeme + "\n";
                        break;
                        case Op_relacional:
                        resultado += "  <Operador relacional>\t" + lexer.lexeme + "\n";
                        break;
                        case Op_atribucion:
                        resultado += "  <Operador atribucion>\t" + lexer.lexeme + "\n";
                        break;
                        case Op_booleano:
                        resultado += "  <Operador booleano>\t" + lexer.lexeme + "\n";
                        break;
                        case Parentesis_a:
                        resultado += "  <Parentesis de apertura>\t" + lexer.lexeme + "\n";
                        break;
                        case Parentesis_c:
                        resultado += "  <Parentesis de cierre>\t" + lexer.lexeme + "\n";
                        break;
                        case LlaveA:
                        resultado += "  <Llave de apertura>\t" + lexer.lexeme + "\n";
                        break;
                        case LlaveC:
                        resultado += "  <Llave de cierre>\t" + lexer.lexeme + "\n";
                        break;*/
                    case CorcheteA:
                        resultado += "  <Corchete de apertura>\t" + lexer.lexeme + "\n";
                        break;
                    case CorcheteC:
                        resultado += "  <Corchete de cierre>\t" + lexer.lexeme + "\n";
                        break;
                        /*case Main:
                        resultado += "  <Reservada main>\t" + lexer.lexeme + "\n";
                        break;
                        case P_coma:
                        resultado += "  <Punto y coma>\t" + lexer.lexeme + "\n";
                        break;
                        case Identificador:
                        resultado += "  <Identificador>\t\t" + lexer.lexeme + "\n";
                        break;
                        case Numero:
                        resultado += "  <Numero>\t\t" + lexer.lexeme + "\n";
                        break;*/
                    case Error:
                        resultado += "  <Simbolo no definido>\n";
                        break;
                    default:
                        resultado += "  < " + lexer.lexeme + " >\n";
                        break;
                }
                Scanner scanner = new Scanner();
                scanner.readFile(expr);
                scanner.organizador();      //Se organiza la lista de Tokens
                
                String columnsTokens[] = {"Token","Tipo","Linea(s)"};
                String columnsErrors[] = {"Error", "Linea"};
                String datosTokens[][] = new String[scanner.getTokensList().size()][3];
                String datosErrores[][] = new String[scanner.getErrores().size()][3];
                for (int i = 0; i < scanner.getTokensList().size(); i++) {
                    String prnt = (String) scanner.getTokensList().get(i).get(0);
                    String prnt2 = (String) scanner.getTokensList().get(i).get(1);
                    String prnt3 = (String) scanner.getTokensList().get(i).get(2);
                    datosTokens[i][0]= prnt;
                    datosTokens[i][1]= prnt2;
                    datosTokens[i][2]= prnt3;
                }
                for (int i = 0; i < scanner.getErrores().size(); i++) {
                    String prnt = (String) scanner.getErrores().get(i).get(0);
                    String prnt2 = (String) scanner.getErrores().get(i).get(1);
                    datosErrores[i][0]= prnt;
                    datosErrores[i][1]= prnt2;
                }
                DefaultTableModel modelTokens = new DefaultTableModel(datosTokens,columnsTokens);
                DefaultTableModel modelErrors = new DefaultTableModel(datosErrores,columnsErrors);
                DefaultTableModel modelSintax = new DefaultTableModel(datosPrueba,columnsTokens);
                DefaultTableModel modelError = new DefaultTableModel(datosPrueba,columnsErrors);
                DefaultTableModel modelLexico = new DefaultTableModel(datosPrueba,columnsTokens);
                
                TablaSintactico.setModel(modelSintax);
                TablaErrorSintactico.setModel(modelError);
                TablaErrorLexico.setModel(modelErrors);
                TablaLexico.setModel(modelTokens);
            } catch (Exception ex) {
                Logger.getLogger(InterfazScanner.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazScanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazScanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazScanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazScanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazScanner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonArchivo;
    private javax.swing.JToggleButton BtnAnalizar;
    private javax.swing.JToggleButton BtnLimpiar;
    private javax.swing.JTable TablaErrorLexico;
    private javax.swing.JTable TablaErrorSintactico;
    private javax.swing.JTable TablaLexico;
    private javax.swing.JTable TablaSintactico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea textoLeer;
    // End of variables declaration//GEN-END:variables
}
